export { default as ProgramsPage } from "./page/ProgramsList";
export { default as MuntalaqPage } from "./tools/muntalaq/page/MuntalaqPage";
export { MuntalaqTool } from "./tools/muntalaq/ui";
export { default as MurtakizPage } from "./tools/murtakiz/page/MurtakizPage";
export { MurtakizTool } from "./tools/murtakiz/ui";
export { default as MasarPage } from "./tools/masar/page/MasarPage";
export { MasarTool } from "./tools/masar/ui";
export { default as MiaadPage } from "./tools/miaad/page/MiaadPage";
export { MiaadTool } from "./tools/miaad/ui";
export { default as MueenPage } from "./tools/mueen/page/MueenPage";
export { MueenTool } from "./tools/mueen/ui";
export { default as MithaqPage } from "./tools/mithaq/page/MithaqPage";
export { MithaqTool } from "./tools/mithaq/ui";
export { default as EthraaPage } from "./tools/ethraa/page/EthraaPage";
export { EthraaTool } from "./tools/ethraa/ui";
export { default as MulhamPage } from "./tools/mulham/page/MulhamPage";
export { MulhamTool } from "./tools/mulham/ui";
